### ISSUE TITLE
GlobalInformation Requerido

### ISSUE THREAD

**Issue by diesgut** [Facturama/facturama-java-sdk#10]
Hola Estimados,
Estoy usando su sdk con el receptor PUBLICO GENERAL y el facturador me responde el siguiente error:

`ERROR FacturamaClient - cfdiToCreate.GlobalInformation: Este Nodo debe existir cuando el atributo Rfc del nodo receptor contiene el valor XXXXXXXX y el valor del atributo Nombre del nodo Receptor contiene el valor 'PUBLICO EN GENERAL'.`

Pero no encuentro un objeto que represente a dicho nodo en sus sdk donde pueda setear esa información.
Gracias por la ayuda.

**Comment by rafa-dx** [comment]
Se añadio nodo GlobalInformation
